services:
  - type: web
    name: banco-app
    plan: free # <--- ADICIONE ESTA LINHA
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: banco-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: banco-db
    plan: free # <--- ADICIONE ESTA LINHA TAMBÃ‰M